name: configlet-lint

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting the tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configlet linting
        run: |
          ./bin/fetch-configlet
          ./bin/configlet lint .

