name: Test Exercises

on: [push, pull_request]

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-24.04

    container:
      image: clfoundation/sbcl
        
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run Tests
        uses: ./.github/actions/perform-system
        with:
          system: test-exercises
          operation: test-system
